# Generated by Django 4.2.7 on 2025-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='photo',
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
